language: node_js
node_js:
  - '10.13.0'
env:
  - ALGO=RS256
before_script:
  - psql -c 'create database travis;' -U postgres
script:
  - cd spaced-repetition-back-end && yarn && yarn test
cache:
  directories:
    -node_modules
sudo: false
